language: java

est:
  post:
    - mvn com.blackducksoftware.integration:hub-maven-plugin:2.0.2:build-bom -Dhub.output.directory=. -Dhub.deploy.bdio=false
    - bash <(curl -s https://copilot.blackducksoftware.com/bash/circle) ./*_bdio.jsonld

# Enable container-based infrastructure, see https://docs.travis-ci.com/user/ci-environment/
sudo: false
